language: python
services:
  - mongodb
before_script:
  - sleep 15
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

before_install: "pip install codecov"
install: "python setup.py install"
script:
  - py.test --cov
after_success:
  codecov
